/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Prikaz.java
 *
 * Created on Mar 5, 2010, 6:57:13 PM
 */

package analizator;

/**
 *
 * @author stevan
 */
public class Prikaz extends javax.swing.JFrame {

    /** Creates new form Prikaz */
    public Prikaz() {
        initComponents();
        tTekstKeyTyped(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tTekst = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        dAnaliziraj = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lBroj = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dRezultati = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Analizator ucestalosti pojavljivanja karaktera");
        setResizable(false);

        jLabel1.setText("Unesite tekst nad kojim je potrebno izvrsiti analizu:");

        tTekst.setColumns(20);
        tTekst.setRows(5);
        tTekst.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tTekstInputMethodTextChanged(evt);
            }
        });
        tTekst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tTekstKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tTekst);

        jLabel3.setText("cvetkovic.stevan@gmail.com");

        dAnaliziraj.setText("Analiziraj");
        dAnaliziraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dAnalizirajActionPerformed(evt);
            }
        });

        jLabel2.setText("Stevan Cvetkovic");

        lBroj.setText(" ");

        jLabel4.setText("Broj karaktera:");

        dRezultati.setText("Rezultati");
        dRezultati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dRezultatiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(lBroj))
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dRezultati, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dAnaliziraj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dAnaliziraj)
                            .addComponent(lBroj)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dRezultati)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dAnalizirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dAnalizirajActionPerformed
        Funkcije f = new Funkcije();

        f.obrada(tTekst.getText().toLowerCase().toCharArray());

        tTekst.setText("");
        tTekstKeyTyped(null);
    }//GEN-LAST:event_dAnalizirajActionPerformed

    private void tTekstInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tTekstInputMethodTextChanged
    }//GEN-LAST:event_tTekstInputMethodTextChanged

    private void tTekstKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tTekstKeyTyped
        String t = tTekst.getText();
        if(t.length() == 0)
            lBroj.setText(Integer.toString(t.length()));
        else
            lBroj.setText(Integer.toString(t.length()+1));
    }//GEN-LAST:event_tTekstKeyTyped

    private void dRezultatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dRezultatiActionPerformed
        Rezultat r = new Rezultat();
        r.setAlwaysOnTop(true);
        r.setLocationRelativeTo(this);
        r.setVisible(true);
    }//GEN-LAST:event_dRezultatiActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prikaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dAnaliziraj;
    private javax.swing.JButton dRezultati;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lBroj;
    private javax.swing.JTextArea tTekst;
    // End of variables declaration//GEN-END:variables

}
