/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Rezultat.java
 *
 * Created on Mar 6, 2010, 2:36:23 PM
 */

package analizator;

/**
 *
 * @author stevan
 */
public class Rezultat extends javax.swing.JDialog {

    /** Creates new form Rezultat */
    private Object[][] podaci = new Object[30][30];

    public Rezultat()
    {
        popuniTabelu();
        initComponents();
    }

    public void popuniTabelu()
    {
        Funkcije f = new Funkcije();
        Azbuka[] niz = new Azbuka[30];
        niz = f.vratiSortiranNiz();

        for(int i=0; i<niz.length; i++)
        {
            podaci[i][0] = niz[i].getSlovo();
            podaci[i][1] = niz[i].getVerovatnoca();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tTabela = new javax.swing.JTable(){
			public boolean isCellEditable(int rowIndex, int vColIndex) {
				return false;
			}
		};

        setTitle("Prikaz rezultata");

        jLabel1.setText("Verovatnoce pojavljivanja slova:");

        tTabela.setModel(new javax.swing.table.DefaultTableModel(

            podaci,
            new String [] {
                "Slovo", "Verovatnoca"
            }
        ));
        tTabela.getTableHeader().setReorderingAllowed(false);
        tTabela.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(tTabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(190, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rezultat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tTabela;
    // End of variables declaration//GEN-END:variables

}
